/**
 * Shared test helpers: fake gh/git executables and process runners.
 *
 * All GitHub/Git interaction in the helper scripts goes through
 * argv-based child processes. Tests point the scripts at fake executables
 * (--gh-bin / PATH) so no real user GitHub account or repository is ever
 * touched.
 */

import { spawnSync } from 'node:child_process'
import { chmodSync, mkdtempSync, mkdirSync, rmSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

export const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)))
export const SCRIPTS = {
  fetchReviewThreads: join(ROOT, 'skills/gh-address-comments/scripts/fetch-review-threads.mjs'),
  inspectPrChecks: join(ROOT, 'skills/gh-fix-ci/scripts/inspect-pr-checks.mjs'),
  publishPreflight: join(ROOT, 'skills/gh-publish/scripts/publish-preflight.mjs'),
}

/** Create a unique temp directory and return it; caller must clean() it. */
export function tempDir(prefix) {
  const dir = mkdtempSync(join(tmpdir(), `${prefix}-`))
  return {
    dir,
    clean() {
      rmSync(dir, { recursive: true, force: true })
    },
  }
}

const FAKE_GH_TEMPLATE = `#!/usr/bin/env node
// Fake gh executable generated by dsh-github-skills tests.
import { readFileSync, writeFileSync, appendFileSync } from 'node:fs'
const SCENARIO = __SCENARIO__
const COUNTERS = __COUNTERS__
const LOG = __LOG__
const args = process.argv.slice(2)
let stdin = ''
try { stdin = readFileSync(0, 'utf8') } catch {}
try { appendFileSync(LOG, JSON.stringify(args) + '\\n') } catch {}
function respond(entry) {
  const e = entry && typeof entry === 'object' ? entry : {}
  if (e.stdout) process.stdout.write(String(e.stdout))
  if (e.stderr) process.stderr.write(String(e.stderr))
  process.exit(typeof e.status === 'number' ? e.status : 0)
}
function nextCall(key) {
  const file = COUNTERS[key]
  if (file === undefined) return 0
  let n = 0
  try { n = Number(readFileSync(file, 'utf8')) || 0 } catch {}
  writeFileSync(file, String(n + 1))
  return n
}
// A scenario value may be a single response object or an array of responses
// consumed sequentially per subcommand. Missing keys return undefined so the
// caller decides the fallback (auth defaults to success; everything else
// fails loudly).
function pick(key) {
  let value = SCENARIO[key]
  if (value === undefined) return undefined
  if (Array.isArray(value)) value = value[Math.min(nextCall(key), value.length - 1)]
  return value
}
function respondRequired(key, value) {
  if (value === undefined) respond({ status: 1, stderr: 'fake gh: no ' + key + ' scenario\\n' })
  return value
}
// Protocol helpers: read a -F key=value pair, the -R repo binding, and the
// --hostname binding.
function flagValue(flag, prefix) {
  for (let i = 0; i < args.length - 1; i += 1) {
    if (args[i] === flag && (prefix === undefined || args[i + 1].startsWith(prefix))) return args[i + 1]
  }
  return undefined
}
function repoBinding() {
  for (let i = 0; i < args.length - 1; i += 1) {
    if (args[i] === '-R') return args[i + 1]
  }
  return undefined
}
function hostnameBinding() {
  for (let i = 0; i < args.length - 1; i += 1) {
    if (args[i] === '--hostname') return args[i + 1]
  }
  return undefined
}
function failMismatch(kind, expected, actual) {
  respond({ status: 1, stderr: 'fake gh: ' + kind + ' mismatch: expected ' + expected + ', got ' + (actual === undefined ? '(none)' : actual) + '\\n' })
}
function assertHost() {
  // Host binding may ride --hostname (auth/api/graphql) or the -R
  // [HOST/]OWNER/REPO selector (pr checks, run view). Either must match.
  const expected = SCENARIO.expectedHost
  if (expected === undefined) return
  const viaFlag = hostnameBinding()
  const viaRepo = repoBinding()
  const ok = viaFlag === expected || (viaRepo !== undefined && viaRepo.startsWith(expected + '/'))
  if (!ok) failMismatch('hostname', expected, viaFlag ?? viaRepo)
}
function assertRepo() {
  // expectedRepo is the full -R selector (e.g. github.com/acme/demo).
  const expected = SCENARIO.expectedRepo
  if (expected === undefined) return
  const actual = repoBinding()
  if (actual !== expected) failMismatch('repo context', expected, actual)
}
function expectedSlug() {
  // owner/repo portion of the -R selector for job-log endpoint checks.
  const selector = SCENARIO.expectedRepo
  if (selector === undefined) return undefined
  const parts = selector.split('/')
  return parts.length >= 2 ? parts.slice(1).join('/') : selector
}
const sub = args[0]
if (sub === 'auth') {
  assertHost()
  respond(pick('auth') ?? { status: 0 })
} else if (sub === 'pr' && args[1] === 'view') {
  assertHost()
  respond(respondRequired('prView', pick('prView')))
} else if (sub === 'pr' && args[1] === 'checks') {
  assertHost()
  assertRepo()
  respond(respondRequired('checks', pick('checks')))
} else if (sub === 'api' && args[1] === 'graphql') {
  // Protocol-aware graphql: scenario.graphql maps each collection to pages
  // keyed by the cursor actually passed in argv. An unexpected cursor or
  // collection fails loudly instead of returning a canned page.
  assertHost()
  const coll = stdin.includes('reviewThreads(first') ? 'threads'
    : stdin.includes('reviews(first') ? 'reviews'
      : stdin.includes('comments(first') ? 'comments' : undefined
  const spec = SCENARIO.graphql
  if (coll === undefined || spec === undefined || typeof spec !== 'object' || !Array.isArray(spec[coll])) {
    respond({ status: 1, stderr: 'fake gh: no graphql scenario for collection ' + String(coll) + '\\n' })
  }
  const cursorKV = flagValue('-F', 'cursor=')
  const cursor = cursorKV === undefined ? undefined : cursorKV.slice('cursor='.length)
  const empty = { nodes: [], pageInfo: { hasNextPage: false, endCursor: null } }
  const page = spec[coll].length === 0
    ? { page: empty }
    : spec[coll].find((p) => (p.cursor === undefined ? cursor === undefined : p.cursor === cursor))
  if (page === undefined) {
    respond({ status: 1, stderr: 'fake gh: no graphql page for ' + coll + ' cursor=' + String(cursor) + '\\n' })
  }
  const numberKV = flagValue('-F', 'number=')
  const number = numberKV === undefined ? 1 : Number(numberKV.slice('number='.length))
  const pr = {
    number, url: 'https://github.com/acme/demo/pull/' + number, title: 't', state: 'OPEN',
    comments: { pageInfo: { hasNextPage: false, endCursor: null }, nodes: [] },
    reviews: { pageInfo: { hasNextPage: false, endCursor: null }, nodes: [] },
    reviewThreads: { pageInfo: { hasNextPage: false, endCursor: null }, nodes: [] },
  }
  const field = coll === 'threads' ? 'reviewThreads' : coll
  pr[field] = page.page
  respond({ status: 0, stdout: JSON.stringify({ data: { repository: { pullRequest: pr } } }) })
} else if (sub === 'api') {
  // Endpoint is the first positional path argument (flags like --hostname
  // may precede it).
  const endpoint = args.find((a) => a.startsWith('/')) ?? ''
  if (endpoint.startsWith('/repos/') && endpoint.endsWith('/logs')) {
    // Job-log endpoint embeds the owner/repo slug (host rides --hostname).
    assertHost()
    const slug = expectedSlug()
    if (slug !== undefined && !endpoint.startsWith('/repos/' + slug + '/actions/jobs/')) {
      respond({ status: 1, stderr: 'fake gh: job log endpoint repo mismatch: ' + endpoint + '\\n' })
    }
    respond(respondRequired('jobLog', pick('jobLog')))
  }
  respond({ status: 1, stderr: 'fake gh: no scenario for api ' + endpoint + '\\n' })
} else if (sub === 'run' && args[1] === 'view' && args.includes('--log')) {
  assertHost()
  assertRepo()
  respond(respondRequired('runLog', pick('runLog')))
} else if (sub === 'run' && args[1] === 'view' && args.includes('--json')) {
  assertHost()
  assertRepo()
  respond(respondRequired('runView', pick('runView')))
} else if (sub === 'repo' && args[1] === 'view') {
  respond(respondRequired('repoView', pick('repoView')))
} else {
  respond({ status: 1, stderr: 'fake gh: unhandled invocation: ' + args.join(' ') + '\\n' })
}
`

/**
 * Create a fake `gh` executable in `dir`.
 * Scenario keys: auth, prView, checks, graphql, runView, runLog, jobLog,
 * repoView, expectedRepo.
 *
 * `graphql` is protocol-aware: `{ comments: [{cursor, page}], reviews: [...],
 * threads: [...] }` where `page` is `{nodes, pageInfo}` and `cursor` is the
 * GraphQL cursor the helper actually passes. A request for an unknown
 * cursor/collection fails loudly. `expectedRepo` (when set) fails any
 * repo-bound call (`pr checks`, `run view`, job log) whose `-R` argument
 * does not match. Missing keys respond with exit 1, so a script that calls
 * an unexpected gh surface fails loudly.
 */
export function createFakeGh(dir, scenario) {
  const counters = {}
  for (const key of ['auth', 'prView', 'checks', 'graphql', 'runView', 'runLog', 'jobLog', 'repoView']) {
    if (scenario[key] !== undefined) {
      counters[key] = join(dir, `.counter-${key}-${Math.random().toString(36).slice(2)}`)
    }
  }
  const script = join(dir, 'gh')
  const log = join(dir, '.invocations.log')
  writeFileSync(script, FAKE_GH_TEMPLATE
    .replace('__SCENARIO__', JSON.stringify(scenario))
    .replace('__COUNTERS__', JSON.stringify(counters))
    .replace('__LOG__', JSON.stringify(log)))
  chmodSync(script, 0o755)
  return { script, log }
}

const FAKE_GIT_TEMPLATE = `#!/usr/bin/env node
// Fake git executable generated by dsh-github-skills tests.
// Records every invocation to a log file; a test's scenario decides
// responses. Write subcommands always fail loudly when failWrites is set.
const SCENARIO = __SCENARIO__
const LOG = __LOG__
const args = process.argv.slice(2)
import('node:fs').then(({ appendFileSync }) => {
  appendFileSync(LOG, JSON.stringify(args) + '\\n')
  const sub = args[0]
  if (SCENARIO.failWrites && ['add','commit','push','reset','stash','checkout','switch','rm','mv','clean','restore'].includes(sub)) {
    process.stderr.write('fake git: write command refused: ' + sub + '\\n')
    process.exit(1)
  }
  const entry = SCENARIO[sub]
  if (entry === undefined) {
    process.stderr.write('fake git: no scenario for ' + sub + '\\n')
    process.exit(1)
  }
  if (typeof entry === 'function') {
    const out = entry(args)
    process.exit(typeof out === 'number' ? out : 0)
  }
  if (entry.stdout) process.stdout.write(entry.stdout)
  if (entry.stderr) process.stderr.write(entry.stderr)
  process.exit(typeof entry.status === 'number' ? entry.status : 0)
})
`

/** Create a fake `git` executable in `dir` that logs all invocations. */
export function createFakeGit(dir, scenario = {}) {
  const log = join(dir, '.git-calls.log')
  const script = join(dir, 'git')
  writeFileSync(script, FAKE_GIT_TEMPLATE
    .replace('__SCENARIO__', JSON.stringify(scenario))
    .replace('__LOG__', JSON.stringify(log)))
  chmodSync(script, 0o755)
  return { script, log }
}

/** Run `node <script> <args...>` and return {status, stdout, stderr}. */
export function runScript(script, args, options = {}) {
  const result = spawnSync(process.execPath, [script, ...args], {
    encoding: 'utf8',
    cwd: options.cwd,
    env: { ...process.env, ...options.env },
    timeout: options.timeout ?? 60_000,
    maxBuffer: 64 * 1024 * 1024,
  })
  return { status: result.status, stdout: result.stdout ?? '', stderr: result.stderr ?? '' }
}

/** Parse a JSON document written to stdout by a helper script. */
export function parseStdoutJson(result) {
  try {
    return JSON.parse(result.stdout)
  } catch (error) {
    throw new Error(`stdout is not JSON (status=${result.status}, stderr=${result.stderr}): ${result.stdout.slice(0, 400)}`)
  }
}

export function readLog(log) {
  if (!existsSync(log)) return []
  return readFileSync(log, 'utf8').trim().split('\n').filter(Boolean).map((line) => JSON.parse(line))
}

/** Initialize a real disposable git repository with a stable identity. */
export function initGitRepo(dir, options = {}) {
  mkdirSync(dir, { recursive: true })
  const run = (args) => {
    const result = spawnSync('git', args, { encoding: 'utf8', cwd: dir })
    if (result.status !== 0) throw new Error(`git ${args.join(' ')} failed: ${result.stderr}`)
    return result.stdout.trim()
  }
  run(['init', '-b', options.branch ?? 'main'])
  run(['config', 'user.email', 'test@example.com'])
  run(['config', 'user.name', 'Test Runner'])
  run(['config', 'commit.gpgsign', 'false'])
  return { run, dir }
}

export function writeFile(dir, relPath, content) {
  const full = join(dir, relPath)
  mkdirSync(dirname(full), { recursive: true })
  writeFileSync(full, content)
  return full
}

export { join }
